[project]
name = "code-blogs-articles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gensim>=4.3.3",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "tiktoken==0.9.0",
    "torch>=2.7.0",
    "transformers>=4.53.2",
]
